# Generated by Django 4.1.1 on 2022-09-22 14:16

import IOU.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOU', '0002_alter_iou_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iou',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[IOU.models.validate_iou_amount]),
        ),
    ]
